Repository kusitms32th-zighang-2/ZIGHANG_ENTERPRISE_PROJECT_FE, pull requests merged in 2025-09, with the labels that each got.

#42 #38 Hotfix: 카카오 로그인 api 재연결
  src/App.tsx
  src/components/login/LoginButton.tsx
  src/pages/Redirect.tsx
Labels: 📬 API

#47 #45 fix: 온보딩 테스트에 따른 회원가입 전 결과값 연결
  src/components/onboarding/Card.tsx
Labels: 📬 API

#51 #36 Feature: 공고 페이지 로켓 애니메이션 구현
  package.json
  pnpm-lock.yaml
  src/assets/lotties/cloud_default.json
  src/assets/lotties/rocket_click_takeoff.json
  src/assets/lotties/rocket_flying.json
  src/assets/lotties/rocket_hover_blink.json
  src/assets/lotties/rocket_idle_float.json
  src/components/onboarding/Card.tsx
  src/components/onboarding/GrowingTextButton.tsx
  src/components/onboarding/start/Card.tsx
  src/components/rocket/RocketAssistant.tsx
  src/components/rocket/RocketText.tsx
  src/pages/Category.tsx
Labels: 🎨 Design

#63 [#58] 마이페이지 수정 기능 구현
  src/apis/edit-myinfo/patchUsersMyPage.ts
  src/components/onboarding/sign-up/JobCategory.tsx
  src/components/profile/UserInfo.tsx
  src/components/signup/Address.tsx
  src/components/signup/Category.tsx
  src/components/signup/Commute.tsx
  src/components/signup/CommutingTime.tsx
  src/components/signup/Education.tsx
  src/components/signup/Experience.tsx
  src/components/signup/JobCategory.tsx
  src/constants/SignUp.ts
  src/pages/Profile.tsx
  src/pages/SignUp.tsx
  src/stores/editMyInfoStore.ts
  src/types/edit-mypage.ts
  src/types/profile.ts
  src/types/signup.ts
  src/utils/sign-up.ts
Labels: ✨ Feat, 🎨 Design, 📬 API

#64 #52 Refactor: qa 사항 반영
  src/assets/lotties/rocket_click_takeoff.json
  src/components/onboarding/Card.tsx
  src/components/onboarding/Footer.tsx
  src/components/onboarding/start/Card.tsx
  src/components/onboarding/test/ResultCard.tsx
  src/components/onboarding/test/RewardChoiceCard.tsx
  src/components/profile/Card.tsx
  src/components/profile/UserInfoBox.tsx
  src/components/rocket/MobileRocketAssistant.tsx
  src/components/rocket/RocketText.tsx
  src/hooks/usePngExport.ts
  src/index.css
  src/pages/Category.tsx
  src/pages/Profile.tsx
  src/pages/SignUp.tsx
  src/pages/onboarding/OnboardingTest.tsx
  src/pages/onboarding/Start.tsx
  src/types/profile.ts
Labels: 🐞 Fix, 💻 Performance

#68 #67 Feature: 2차 qa 사항 반영
  src/assets/lotties/onboarding_start.json
  src/components/onboarding/start/Card.tsx
  src/pages/onboarding/OnboardingTest.tsx
Labels: 🎨 Design

#74 #73 Fix: 카카오 로그아웃 api 연결 로직 수정
  src/apis/logout.ts
  src/components/profile/UserInfo.tsx
Labels: 🐞 Fix, 📬 API

#90 #86 Hotfix: 온보딩 캐릭터 발급시 발생하는 오류 수정
  src/apis/api.ts
  src/components/onboarding/Card.tsx
  src/components/onboarding/Footer.tsx
  src/components/profile/Card.tsx
  src/constants/OnboardingResult.ts
Labels: 🐞 Fix
